feat: SHH deploy12

diff --git a/.github/workflows/laravel.yml b/.github/workflows/laravel.yml
--- a/.github/workflows/laravel.yml
+++ b/.github/workflows/laravel.yml
@@ -63,8 +63,8 @@ jobs:
           USERNAME: ${{ secrets.USERNAME }}
           PASSWORD: ${{ secrets.PASSWORD }}
         run: |
-          # Instalar sshpass para pasar la contraseña
-          sudo apt-get install -y sshpass
+          # Instalar sshpass y npm para asegurar que todo esté disponible
+          sudo apt-get install -y sshpass nodejs npm sudo
           
           # Verificar si la conexión SSH funciona correctamente
           echo "Verificando la conexión SSH con: $USERNAME@$HOST:$PORT"
@@ -89,6 +89,12 @@ jobs:
           # Asegurarse de estar en el directorio correcto
           cd $HOME/domains/koalacordisimple.jcomtec.com
 
+          # Verificar si el repositorio se clonó correctamente
+          if [ ! -d ".git" ]; then
+            echo "El directorio no es un repositorio Git. Abortando despliegue."
+            exit 1
+          fi
+
           # Actualizar el repositorio
           git pull origin main  # Asegurarse de tener la última versión del repositorio
 
@@ -104,10 +110,15 @@ jobs:
           fi
 
           # Ejecutar comandos de Laravel
-          php artisan key:generate  # Generar la clave de la aplicación
-          php artisan config:cache  # Limpiar caché de configuración
-          php artisan route:cache  # Limpiar caché de rutas
-          php artisan migrate --force  # Ejecutar migraciones
-          sudo chown -R www-data:www-data storage bootstrap/cache  # Ajustar permisos
+          if [ -f "artisan" ]; then
+            php artisan key:generate  # Generar la clave de la aplicación
+            php artisan config:cache  # Limpiar caché de configuración
+            php artisan route:cache  # Limpiar caché de rutas
+            php artisan migrate --force  # Ejecutar migraciones
+            sudo chown -R www-data:www-data storage bootstrap/cache  # Ajustar permisos
+          else
+            echo "No se encontró el archivo artisan. Abortando despliegue."
+            exit 1
+          fi
 
           EOF
